### ISSUE TITLE
Multiple mobs causings targeting delay

### ISSUE THREAD

**Issue by lightnencruser** [Selindrile/SendAllTarget#1]
While testing in Dyna D there was a considerable lag while sending the alt a request to target.  Seems that when more than 2 mobs re up the request isn't always sent.

**Comment by Selindrile** [comment]
I've heard something similar from someone else as well though I've no idea what could be causing it.

**Comment by lightnencruser** [comment]
The only thing I can assume now that Ive been playing with it is there must be a packet issue when to many mobs are loaded. I can target Erinys easily but when in Dyna it freaks out.

**Comment by Selindrile** [comment]
I'm not sure what exactly it is, we fake an incoming packet to get our target, so we shouldn't (in theory) be dependent on latency or the server in any way.

**Comment by Pacoman69** [comment]
Is there a way to make it so it doesn't lock on to the mob?  Not a  good thing if you have your other characters on follow...

**Comment by Selindrile** [comment]
There is not, it's a limitation of the packet we use that Arcon exposed.
