### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by Jessikon** [Selindrile/SendAllTarget#2]
Just came back to the game after 8 years and found your addons very useful. Is there some way to use sendalltarget to target npc's or objects with alts? Not just enemies. Would be super handy while doing missions! If not thanks for your time and all the cool stuff still :)

**Comment by Selindrile** [comment]
Some NPCs will work fine with this, others will not, unfortunately the only current way with windower to force a target (without tabbing around) is by abusing the Assist packet, so this will only work on NPCs that the assist packet will work with, try just using //sat alltarget, some NPCs will work, others will not, unfortunately, and there's no way around that I I'm aware of except for implementing mass tab targetting, which I don't really want to do. :/
