### ISSUE TITLE
Detargeting during certain events

### ISSUE THREAD

**Issue by The-Aerec** [Selindrile/SendAllTarget#4]
Sendalltarget constantly causes the alt window to untarget during certain events. I have only able been able to reproduce this on Gaes Fate mobs. The alt character will be engaged and attacking but unable to weaponskill due to the window thinking the alt is not targeting the mob. I have posted a window below to show what this looks like. (/lockon) Doesn't fix this, as it will immediately untarget the mob. 

![issue](https://user-images.githubusercontent.com/6257062/92062263-4cd9a300-ed66-11ea-82ec-bcf686cb7261.png)

**Comment by Selindrile** [comment]
You can take a look at the code: https://github.com/Selindrile/SendAllTarget/blob/master/SendAllTarget.lua

Sendalltarget doesn't do anything on it's own during events, it only responds to commands, not anything else, the entirety of it's function is within: windower.register_event('addon command'
