### ISSUE TITLE
Some commands not working

### ISSUE THREAD

**Issue by khumaffxi** [Selindrile/SendAllTarget#5]
Hi. First thanks for making such an awesome addon.   I'm trying to use your addon to multibox pups.  I am using the send and shortcuts addons as well. Here is what is working for me and what is not:

//sat alltarget and //sat youtarget - working great!
//sat allattack and //sat youattack - working great!

//sat target and //sat attack - both return an error saying "bad argument on #1, number expected received nil" (i don't understand how you would actually utilize these commands. As i understand it they control the box you are already on, which seems redundant,)

//sat allcommand and //sat youcommand - both of these send a command to my characters, but it is looks like it tries to process it as a number and not as a mob id and results in an input error. I.e. if i type in "//sat allcommand deploy" to engage my puppets onto my current box's targeted mob each box on my computer receives the command "/ja deploy 17260806" which results in a "... a command error occured." 
![Capture](https://user-images.githubusercontent.com/78102533/106035249-81455700-6099-11eb-98f0-1f2110c8d0ba.PNG)
//sat youcommand has the same issue.  I have tried this with spells with both commands as well, and the results are the same.  I'm fairly new to windower and addons so maybe i'm just missing something obvious.  Any help you can offer is appreciated.  Thank you!

**Comment by Selindrile** [comment]
From the readme:
//sat target - This box targets the ID provided.
//sat attack - This box attacks the ID provided.

The number it's expecting the mobID, which you're not providing, thus the 'nil'.

For allcommand and youcommand, it's sending the command, the number is the mob in question's mobid, however you'll need an addon (such as Gearswap), again as it says in the readme: "* Addon created to make Send more useful in terms of targetting, may require a loaded gearswap user file." The word "may" there is in case the user has another addon that will catch the command with a mobID and convert it.

**Comment by khumaffxi** [comment]
Thanks for the quick response. I did read that and I do have gearswap installed, but I have not set up anything in it yet. It sounds like that is what I need to do to make it work. I'll try that. Thanks again for the help.
